from .delivery import DeliveryJob


JOBS = {
    "São Paulo": DeliveryJob(
        "São Paulo",
        "Rio de Janeiro",
        payment=100,
        minimum_quality=0.0,
        acceptance_chance=1.0,
    ),
    "Rio de Janeiro": DeliveryJob(
        "Rio de Janeiro",
        "Minas Gerais",
        payment=125,
        minimum_quality=0.05,
        acceptance_chance=0.85,
    ),
    "Minas Gerais": DeliveryJob(
        "Minas Gerais",
        "São Paulo",
        payment=120,
        minimum_quality=0.05,
        acceptance_chance=0.85,
    ),
    "Paraná": DeliveryJob(
        "Paraná",
        "Santa Catarina",
        payment=115,
        minimum_quality=0.05,
        acceptance_chance=0.82,
    ),
    "Rio Grande do Sul": DeliveryJob(
        "Rio Grande do Sul",
        "Santa Catarina",
        payment=115,
        minimum_quality=0.08,
        acceptance_chance=0.80,
    ),
    "Santa Catarina": DeliveryJob(
        "Santa Catarina",
        "Paraná",
        payment=130,
        minimum_quality=0.10,
        acceptance_chance=0.78,
    ),
    "Bahia": DeliveryJob(
        "Bahia",
        "Pernambuco",
        payment=95,
        minimum_quality=0.05,
        acceptance_chance=0.82,
    ),
    "Goiás": DeliveryJob(
        "Goiás",
        "Distrito Federal",
        payment=105,
        minimum_quality=0.05,
        acceptance_chance=0.80,
    ),
    "Pernambuco": DeliveryJob(
        "Pernambuco",
        "Ceará",
        payment=95,
        minimum_quality=0.08,
        acceptance_chance=0.75,
    ),
    "Pará": DeliveryJob(
        "Pará",
        "Amazonas",
        payment=90,
        minimum_quality=0.10,
        acceptance_chance=0.72,
    ),
    "Ceará": DeliveryJob(
        "Ceará",
        "Rio Grande do Norte",
        payment=90,
        minimum_quality=0.10,
        acceptance_chance=0.74,
    ),
    "Espírito Santo": DeliveryJob(
        "Espírito Santo",
        "Rio de Janeiro",
        payment=120,
        minimum_quality=0.10,
        acceptance_chance=0.76,
    ),
    "Mato Grosso": DeliveryJob(
        "Mato Grosso",
        "Goiás",
        payment=125,
        minimum_quality=0.12,
        acceptance_chance=0.70,
    ),
    "Mato Grosso do Sul": DeliveryJob(
        "Mato Grosso do Sul",
        "Paraná",
        payment=110,
        minimum_quality=0.10,
        acceptance_chance=0.72,
    ),
    "Amazonas": DeliveryJob(
        "Amazonas",
        "Pará",
        payment=105,
        minimum_quality=0.15,
        acceptance_chance=0.65,
    ),
    "Maranhão": DeliveryJob(
        "Maranhão",
        "Piauí",
        payment=80,
        minimum_quality=0.12,
        acceptance_chance=0.65,
    ),
    "Paraíba": DeliveryJob(
        "Paraíba",
        "Pernambuco",
        payment=85,
        minimum_quality=0.12,
        acceptance_chance=0.68,
    ),
    "Rio Grande do Norte": DeliveryJob(
        "Rio Grande do Norte",
        "Ceará",
        payment=90,
        minimum_quality=0.12,
        acceptance_chance=0.68,
    ),
    "Alagoas": DeliveryJob(
        "Alagoas",
        "Pernambuco",
        payment=80,
        minimum_quality=0.15,
        acceptance_chance=0.62,
    ),
    "Sergipe": DeliveryJob(
        "Sergipe",
        "Alagoas",
        payment=85,
        minimum_quality=0.15,
        acceptance_chance=0.65,
    ),
    "Piauí": DeliveryJob(
        "Piauí",
        "Maranhão",
        payment=75,
        minimum_quality=0.15,
        acceptance_chance=0.60,
    ),
    "Rondônia": DeliveryJob(
        "Rondônia",
        "Mato Grosso",
        payment=100,
        minimum_quality=0.15,
        acceptance_chance=0.65,
    ),
    "Tocantins": DeliveryJob(
        "Tocantins",
        "Goiás",
        payment=95,
        minimum_quality=0.15,
        acceptance_chance=0.62,
    ),
    "Acre": DeliveryJob(
        "Acre",
        "Rondônia",
        payment=75,
        minimum_quality=0.20,
        acceptance_chance=0.55,
    ),
    "Amapá": DeliveryJob(
        "Amapá",
        "Pará",
        payment=80,
        minimum_quality=0.20,
        acceptance_chance=0.55,
    ),
    "Roraima": DeliveryJob(
        "Roraima",
        "Amazonas",
        payment=85,
        minimum_quality=0.20,
        acceptance_chance=0.55,
    ),
    "Distrito Federal": DeliveryJob(
        "Distrito Federal",
        "Goiás",
        payment=150,
        minimum_quality=0.20,
        acceptance_chance=0.70,
    ),
}
